<?php
// The owner's numbers page. Generated by build.mjs; edit it there.
$EDIT_USER = "Silverbauer";
$EDIT_HASH = '$2y$10$YM3U3P.TEB3.lr00uXCsbeNQW852A2Xdg/Rwbro4BIJULUT7bHiz2';
header('Cache-Control: no-store, private');
header('X-Robots-Tag: noindex');
function edit_key() {
  global $EDIT_HASH;
  static $k = null;
  if ($k !== null) return $k;
  $file = dirname($_SERVER['DOCUMENT_ROOT']) . '/phillyafterschool-edit.key';
  $raw = @file_get_contents($file);
  if ($raw === false || strlen(trim($raw)) !== 64) {
    $raw = bin2hex(random_bytes(32));
    if (@file_put_contents($file, $raw, LOCK_EX) === false) { http_response_code(503); exit('Signing in is not available right now.'); }
    @chmod($file, 0600);
    $raw = (string) @file_get_contents($file);   // if two requests raced, both read back the same key
  }
  $k = hash_hmac('sha256', $EDIT_HASH . '|edit-sign-in', trim($raw));
  return $k;
}
function edit_token($exp) {
  return $exp . '.' . hash_hmac('sha256', (string) $exp, edit_key());
}
function edit_signed_in() {
  if (!isset($_COOKIE['pas_edit']) || !is_string($_COOKIE['pas_edit'])) return false;
  $parts = explode('.', $_COOKIE['pas_edit'], 2);
  if (count($parts) !== 2 || !ctype_digit($parts[0]) || (int) $parts[0] < time()) return false;
  return hash_equals(edit_token($parts[0]), $_COOKIE['pas_edit']);
}

if (!edit_signed_in()) { header('Location: ../', true, 303); exit; }
$SCHOOLS = json_decode('{"nebinger":"Nebinger","meredith":"Meredith","coppin":"Coppin","vare-washington":"Vare-Washington","mccall":"McCall"}', true);
$file = dirname($_SERVER['DOCUMENT_ROOT']) . '/phillyafterschool-data/groups.sqlite';
$have = is_file($file);
$tiles = array(); $bySchool = array(); $days = array(); $ever = array();
$cols = array('account' => 'New accounts', 'signin_email' => 'Sign-ins by email', 'signin_google' => 'Sign-ins with Google', 'week_saved' => 'Weeks kept', 'school_saved' => 'Schools kept', 'grades_saved' => 'Grades kept', 'share' => 'Weeks shared with one person', 'group' => 'Groups started', 'invite' => 'Invitations', 'join' => 'Invitations accepted', 'account_deleted' => 'Accounts deleted');
if ($have) {
  try {
    $db = new PDO('sqlite:' . $file);
    $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    $db->exec('PRAGMA busy_timeout=3000');
  } catch (Exception $e) { $have = false; }
}
if ($have) {
  // A question the database can't answer yet (a table added in a later version) counts as zero.
  $n = function ($sql, $args = array()) use ($db) { try { $st = $db->prepare($sql); $st->execute($args); return (int) $st->fetchColumn(); } catch (Exception $e) { return 0; } };
  $t = time();
  $byGrade = array();
  try { foreach ($db->query("SELECT grades FROM users WHERE grades != ''") as $r) foreach (explode(',', $r['grades']) as $g) $byGrade[$g] = (isset($byGrade[$g]) ? $byGrade[$g] : 0) + 1; } catch (Exception $e) { /* before grades existed */ }
  $gradeLine = '';
  foreach (array('PK', 'K', '1', '2', '3', '4', '5', '6', '7', '8') as $g) { if (isset($byGrade[$g])) $gradeLine .= ($gradeLine === '' ? '' : ', ') . $g . ': ' . $byGrade[$g]; }
  $accounts = $n('SELECT COUNT(*) FROM users');
  $tiles[] = array($accounts, 'accounts', $n('SELECT COUNT(*) FROM users WHERE created > ?', array($t - 7 * 86400)) . ' new in 7 days, ' . $n('SELECT COUNT(*) FROM users WHERE created > ?', array($t - 30 * 86400)) . ' in 30');
  $tiles[] = array($n('SELECT COUNT(DISTINCT user_id) FROM sessions WHERE seen > ?', array($t - 30 * 86400)), 'people signed in during the last 30 days', '');
  $tiles[] = array($n("SELECT COUNT(*) FROM users WHERE via = 'google'"), 'accounts made with Google', ($accounts - $n("SELECT COUNT(*) FROM users WHERE via = 'google'")) . ' made with an emailed code');
  $tiles[] = array($n('SELECT COUNT(*) FROM users WHERE listed = 1'), 'accounts added to the email list', $n("SELECT COUNT(*) FROM users WHERE first = ''") . ' accounts haven’t added a name yet');
  $tiles[] = array($n("SELECT COUNT(*) FROM users WHERE school != ''"), 'profiles with a school kept', '');
  $tiles[] = array($n("SELECT COUNT(*) FROM users WHERE grades != ''"), 'profiles with grades kept', $gradeLine);
  $tiles[] = array($n('SELECT COUNT(*) FROM weeks'), 'weeks kept in profiles', 'by ' . $n('SELECT COUNT(DISTINCT user_id) FROM weeks') . ' people');
  $tiles[] = array($n('SELECT COUNT(*) FROM grp WHERE solo = 1 AND expires > ?', array($t)), 'weeks shared with one person or more', $n('SELECT COUNT(*) FROM members m JOIN grp g ON g.id = m.group_id WHERE g.solo = 1 AND m.role != ?', array('owner')) . ' people have opened one');
  $tiles[] = array($n('SELECT COUNT(*) FROM grp WHERE solo = 0 AND expires > ?', array($t)), 'groups', $n("SELECT COUNT(*) FROM (SELECT g.id FROM grp g JOIN members m ON m.group_id = g.id WHERE g.solo = 0 AND m.status = 'approved' GROUP BY g.id HAVING COUNT(*) >= 2)") . ' have two or more adults; the biggest has ' . $n("SELECT COALESCE(MAX(c), 0) FROM (SELECT COUNT(*) AS c FROM members m JOIN grp g ON g.id = m.group_id WHERE g.solo = 0 AND m.status = 'approved' GROUP BY m.group_id)"));
  $tiles[] = array($n("SELECT COUNT(DISTINCT m.user_id) FROM members m JOIN grp g ON g.id = m.group_id WHERE g.solo = 0 AND m.status = 'approved'"), 'adults in groups', $n('SELECT COUNT(*) FROM kids k JOIN members m ON m.id = k.member_id JOIN grp g ON g.id = m.group_id WHERE g.solo = 0') . ' children’s weeks in them');
  $invites = $n('SELECT COUNT(*) FROM invites');
  $joined = $n('SELECT COUNT(*) FROM invites i WHERE EXISTS (SELECT 1 FROM members m JOIN users u ON u.id = m.user_id WHERE m.group_id = i.group_id AND u.email = i.email)');
  $tiles[] = array($invites, 'invitations outstanding or accepted', $joined . ' accepted, ' . ($invites - $joined) . ' not yet');
  try {
    foreach ($db->query("SELECT school, COUNT(*) AS c FROM users WHERE school != '' GROUP BY school ORDER BY c DESC, school") as $r) $bySchool[] = array(isset($SCHOOLS[$r['school']]) ? $SCHOOLS[$r['school']] : $r['school'], (int) $r['c']);
  } catch (Exception $e) { /* before profiles existed */ }
  $tz = new DateTimeZone('America/New_York');
  for ($i = 0; $i < 30; $i++) { $d = new DateTime('now', $tz); $d->modify('-' . $i . ' day'); $days[$d->format('Y-m-d')] = array(); }
  try {
    foreach ($db->query('SELECT k, day, n FROM tally') as $r) {
      if (!isset($cols[$r['k']])) continue;
      $ever[$r['k']] = (isset($ever[$r['k']]) ? $ever[$r['k']] : 0) + (int) $r['n'];
      if (isset($days[$r['day']])) $days[$r['day']][$r['k']] = (int) $r['n'];
    }
  } catch (Exception $e) { /* before counting began */ }
}
// One number for the table: today (1), yesterday (-1), the last N days including today, or ever (0).
$sum = function ($key, $span) use (&$days, &$ever) {
  if ($span === 0) return isset($ever[$key]) ? $ever[$key] : 0;
  $rows = array_values($days);
  if ($span === -1) return isset($rows[1][$key]) ? $rows[1][$key] : 0;
  $t = 0;
  for ($i = 0; $i < $span && $i < count($rows); $i++) $t += isset($rows[$i][$key]) ? $rows[$i][$key] : 0;
  return $t;
};
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>Site numbers | Philly After School</title>
<meta name="description" content="Counts of accounts, shared weeks and groups.">
<link rel="canonical" href="https://phillyafterschool.org/edit/stats/">
<meta name="robots" content="noindex">
<meta property="og:title" content="Site numbers | Philly After School">
<meta property="og:description" content="Counts of accounts, shared weeks and groups.">
<meta property="og:type" content="website">
<meta property="og:url" content="https://phillyafterschool.org/edit/stats/">
<meta property="og:site_name" content="Philly After School">
<meta property="og:image" content="https://phillyafterschool.org/share.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="Philly After School: a row of Philadelphia rowhouses, a school and a yellow school bus">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="../../favicon.svg" type="image/svg+xml">
<link rel="icon" href="../../favicon.png" type="image/png" sizes="48x48">
<link rel="apple-touch-icon" href="../../apple-touch-icon.png">
<meta name="theme-color" content="#0F4D90">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Archivo:wdth,wght@62..125,400..900&family=Atkinson+Hyperlegible:wght@400;700&display=swap">
<link rel="stylesheet" href="../../assets/site.css?v=faccb22b">
</head>
<body>
<script>document.documentElement.className+=' js';try{if(localStorage.getItem('pas-in')==='1')document.documentElement.className+=' signed'}catch(e){}</script>
<div class="band topstrip when-out"><div class="topbar"><div class="in">
    <span>Already have an account?</span><a href="../../account/">Log in</a>
  </div></div></div>
<header class="band sitebar">
  <div class="in bar">
    <a class="brand" href="../../"><span class="bus-mark"></span>Philly After School</a>
    <button type="button" class="menu-btn" aria-expanded="false" aria-controls="site-nav"><span class="menu-bars" aria-hidden="true"></span>Menu</button>
    <nav class="nav" id="site-nav" aria-label="Site"><details class="menu"><summary>Programs</summary><ul><li><a href="../../programs/">After-school programs</a></li><li><a href="../../days-off/">Day-camp programs</a></li></ul></details><details class="menu"><summary>Search by</summary><ul><li><a href="../../schools/">School</a></li><li><a href="../../neighborhoods/">Neighborhood</a></li><li><a href="../../types/">Program type</a></li><li><a href="../../programs/#by-day">Day of week</a></li></ul></details><details class="menu"><summary>Build a schedule<span class="count" data-board-count hidden></span></summary><ul><li><a href="../../board/">After-school schedule</a></li><li><a href="../../days-off/#plan">Day-camp schedule</a></li></ul></details><details class="menu"><summary>Suggest</summary><ul><li><a href="../../suggest/">A program</a></li><li><a href="../../ideas/">A feature</a></li><li><a href="../../schools/request/">A school</a></li></ul></details><a href="../../about/">About</a><a class="nav-cta when-out" href="../../register/">Create a free account</a><a class="nav-cta when-in" href="../../account/">Your account</a></nav>
  </div>
</header>
<div class="band pagehead">
  <div class="in hero">
    <h1>Site numbers</h1>
    <p class="lede">Accounts, profiles, shared weeks and groups. Counts only: no names, addresses or weeks are shown here.</p>
  </div>
  
</div>
<main class="wrap">
<div class="prose stats">
<?php if (!$have) { ?>
  <div class="panel"><p>Nobody has made an account yet, so there is nothing to count.</p></div>
<?php } else { ?>
  <h2>Right now</h2>
  <div class="stat-grid">
    <?php foreach ($tiles as $tile) { ?><div class="stat"><b><?php echo number_format($tile[0]); ?></b><span><?php echo htmlspecialchars($tile[1], ENT_QUOTES, 'UTF-8'); ?></span><?php if ($tile[2] !== '') { ?><small><?php echo htmlspecialchars($tile[2], ENT_QUOTES, 'UTF-8'); ?></small><?php } ?></div><?php } ?>
  </div>
  <h2>Schools kept in profiles</h2>
  <?php if (!$bySchool) { ?><p class="hint">None yet.</p><?php } else { ?>
  <table class="stat-table"><tbody><?php foreach ($bySchool as $row) { ?><tr><th scope="row"><?php echo htmlspecialchars($row[0], ENT_QUOTES, 'UTF-8'); ?></th><td><?php echo number_format($row[1]); ?></td></tr><?php } ?></tbody></table>
  <?php } ?>
  <h2>What happened, and when</h2>
  <div class="stat-scroll"><table class="stat-table">
    <thead><tr><th scope="col"></th><th scope="col">Today</th><th scope="col">Yesterday</th><th scope="col">Last 7 days</th><th scope="col">Last 30 days</th><th scope="col">Ever</th></tr></thead>
    <tbody>
    <?php foreach ($cols as $key => $label) { ?><tr><th scope="row"><?php echo htmlspecialchars($label, ENT_QUOTES, 'UTF-8'); ?></th><?php foreach (array(1, -1, 7, 30, 0) as $span) { $v = $sum($key, $span); ?><td><?php echo $v ? number_format($v) : '<span class="nil">0</span>'; ?></td><?php } ?></tr><?php } ?>
    </tbody>
  </table></div>
  <p class="hint">“Ever” counts everything since accounts began, including accounts and groups that were later deleted. Sign-ins by method and profile saves have been counted since October 6, 2026. Days are Philadelphia days, and “last 7 days” includes today.</p>
<?php } ?>
  <p><a class="btn" href="../">Back to editing</a> <a class="btn" href="../?out=1">Sign out</a></p>
</div>
</main>
<footer class="foot"><div class="in">
  <nav class="foot-cols" aria-label="Footer">
    <div class="foot-brand">
      <a class="brand" href="../../"><span class="bus-mark"></span>Philly After School</a>
      <p><span data-copy="2ded0fc514">After-school programs in Philadelphia, sorted by the school your child goes to.</span></p>
      <p class="foot-support"><span><span data-copy="e877ba88ef">Free, and run by one parent.</span></span> <a class="btn foot-cta" href="../../support/">Help the site keep going</a></p>
    </div>
    <div>
      <h2><a href="../../schools/"><span data-copy="06c76a46e4">Schools</span></a></h2>
      <ul>
        <li><a href="../../schools/"><span data-copy="0898b0b426">All schools</span></a></li>
        <li><a href="../../neighborhoods/"><span data-copy="8ed176874c">By neighborhood</span></a></li>
        <li><a href="../../schools/request/"><span data-copy="6c51011791">Ask for your school</span></a></li>
      </ul>
    </div>
    <div>
      <h2><a href="../../programs/"><span data-copy="ab14d0a7db">Programs</span></a></h2>
      <ul>
        <li><a href="../../programs/"><span data-copy="b8741ed7c0">All programs, A to Z</span></a></li>
        <li><a href="../../types/"><span data-copy="3e6c889cad">Programs by type</span></a></li>
        <li><a href="../../neighborhoods/"><span data-copy="3a356e1883">Programs by neighborhood</span></a></li>
        <li><a href="../../days-off/"><span data-copy="fb556467b7">Day-camp programs</span></a></li>
        <li><a href="../../suggest/"><span data-copy="0d1fc1aeaa">Suggest a program</span></a></li>
        <li><a href="../../review/"><span data-copy="d2684e6248">Write a review</span></a></li>
      </ul>
    </div>
    <div>
      <h2><a href="../../board/"><span data-copy="928655b7f0">Your family</span></a></h2>
      <ul>
        <li><a href="../../board/"><span data-copy="55cf06857b">After-school schedule</span></a></li>
        <li><a href="../../days-off/#plan"><span data-copy="ef8a7dc9b4">Day-camp schedule</span></a></li>
        <li><a href="../../alerts/"><span data-copy="d4819c397f">Dates by email</span></a></li>
        <li><a href="../../account/"><span data-copy="4ab2910209">Your account</span></a></li>
      </ul>
    </div>
    <div>
      <h2><a href="../../about/"><span data-copy="6b21fb791a">About</span></a></h2>
      <ul>
        <li><a href="../../about/"><span data-copy="5e461a2404">About this site</span></a></li>
        <li><a href="../../about/#how"><span data-copy="5b2fc57ac3">How listings are checked</span></a></li>
        <li><a href="../../about/#corrections"><span data-copy="1862eb688d">Send a correction</span></a></li>
        <li><a href="../../ideas/"><span data-copy="29c269f6e8">Request a feature</span></a></li>
        <li><a href="../../privacy/"><span data-copy="cf01481f62">Privacy</span></a></li>
        <li><a href="../../support/"><span data-copy="fd1482eac6">Buy me a coffee</span></a></li>
      </ul>
    </div>
  </nav>
  <div class="foot-fine">
    <p><span data-copy="b7e5078568">Listings come from each provider’s public pages and are not endorsements. Prices, hours and pickup routes change, so confirm with the provider before you enroll.</span></p>
    <p><span data-copy="ab9dba162b" data-tpl="{site} is an independent community project. It is not affiliated with the School District of Philadelphia or any provider listed." data-vars="{&quot;site&quot;:&quot;Philly After School&quot;}">Philly After School is an independent community project. It is not affiliated with the School District of Philadelphia or any provider listed.</span></p>
    <p>Built by <a href="https://joshsilverbauer.com" target="_blank" rel="noopener">Josh Silverbauer</a>.</p>
  </div>
</div></footer>
<script src="../../assets/site.js?v=584ebb86" data-edit="{&quot;js&quot;:&quot;../../assets/edit.js?v=29a85f54&quot;,&quot;send&quot;:&quot;../../edit/send.php&quot;,&quot;home&quot;:&quot;../../edit/&quot;,&quot;contact&quot;:&quot;contact@phillyafterschool.org&quot;}" data-api="../../groups/api.php"></script>

</body>
</html>
