<?php
// Receives the contact form. Generated by build.mjs; edit it there.
$TO = "contact@phillyafterschool.org";
$SITE = "Philly After School";

function fail($msg, $code) {
  http_response_code($code);
  header('Content-Type: text/html; charset=utf-8');
  echo '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Not sent</title><link rel="stylesheet" href="../assets/site.css?v=05edd678"></head><body><main class="wrap"><h1>That did not send</h1><p>' . htmlspecialchars($msg, ENT_QUOTES, 'UTF-8') . '</p><p><a href="./">Go back and try again</a></p></main></body></html>';
  exit;
}
function field($key, $max) {
  $v = (isset($_POST[$key]) && is_string($_POST[$key])) ? trim($_POST[$key]) : '';
  $v = str_replace(chr(0), '', $v);
  return function_exists('mb_substr') ? mb_substr($v, 0, $max, 'UTF-8') : substr($v, 0, $max);
}
function one_line($v) {
  return trim(preg_replace('/[\r\n\t]+/', ' ', $v));
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
  header('Location: ./', true, 303);
  exit;
}
// A hidden field people never see. If it is filled in, a bot did it: act as if it worked.
if (field('company', 200) !== '') {
  header('Location: thanks/', true, 303);
  exit;
}
$name = one_line(field('name', 100));
$email = one_line(field('email', 150));
$topic = one_line(field('topic', 60));
$message = field('message', 4000);
if ($message === '') fail('Please write a message.', 400);
if (!filter_var($email, FILTER_VALIDATE_EMAIL)) fail('Please add your email address, so we can write back.', 400);
if (substr_count(strtolower($message), 'http') > 4) fail('That has too many links for us to accept. Please trim it and try again.', 400);
// At most 5 messages from one address in an hour.
$file = dirname($_SERVER['DOCUMENT_ROOT']) . '/phillyafterschool-contact-times.json';
$who = substr(hash('sha256', isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : ''), 0, 16);
$times = @json_decode((string) @file_get_contents($file), true);
if (!is_array($times)) $times = array();
$recent = array();
foreach ($times as $k => $list) { if (!is_array($list)) continue; $keep = array(); foreach ($list as $t) { if (is_int($t) && $t > time() - 3600) $keep[] = $t; } if ($keep) $recent[$k] = $keep; }
if (isset($recent[$who]) && count($recent[$who]) >= 5) fail('That’s a lot of messages in an hour. Please try again later, or email ' . $TO . '.', 429);
$recent[$who][] = time();
@file_put_contents($file, json_encode($recent), LOCK_EX);

$body = "Topic: $topic\n" . "Name: $name\n" . "Email: $email\n\n" . "Message:\n$message\n";
$subject = one_line("[$SITE] Contact: $topic" . ($name !== '' ? " ($name)" : ''));
$headers = array('From: ' . $SITE . ' <' . $TO . '>', 'Reply-To: ' . $email, 'MIME-Version: 1.0', 'Content-Type: text/plain; charset=UTF-8');
$sent = @mail($TO, '=?UTF-8?B?' . base64_encode($subject) . '?=', $body, implode("\r\n", $headers));
$log = dirname($_SERVER['DOCUMENT_ROOT']) . '/phillyafterschool-suggestions.log';
$saved = @file_put_contents($log, date('c') . ($sent ? ' (emailed)' : ' (EMAIL FAILED)') . "\n" . $body . "----\n", FILE_APPEND | LOCK_EX);
if (!$sent && $saved === false) fail('Something went wrong on our side. Please email ' . $TO . ' instead.', 500);
header('Location: thanks/', true, 303);
exit;
