<?php
// Receives the "Write a review" form. Generated by build.mjs; edit it there.
// ----- sending mail: Postmark when its key is on the server, else the host's own mail. Generated by build.mjs. -----
function pas_mail_key() {
  static $k = null;
  if ($k !== null) return $k;
  $raw = @file_get_contents(dirname((string) $_SERVER['DOCUMENT_ROOT']) . '/phillyafterschool-postmark.key');
  $raw = is_string($raw) ? trim($raw) : '';
  $k = preg_match('/^[0-9a-fA-F]{8}(-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12}$/', $raw) ? $raw : '';
  return $k;
}
function pas_mail_via() { return (pas_mail_key() !== '' && function_exists('curl_init')) ? 'postmark' : 'host'; }
// A count for the day and the service's last answer. Numbers and a code only: never an address or a subject.
function pas_mail_note($how, $result) {
  $file = dirname((string) $_SERVER['DOCUMENT_ROOT']) . '/phillyafterschool-mail.json';
  $d = json_decode((string) @file_get_contents($file), true);
  $day = gmdate('Y-m-d');
  if (!is_array($d) || !isset($d['day']) || $d['day'] !== $day) $d = array('day' => $day, 'postmark' => 0, 'host' => 0, 'failed' => 0, 'last' => (is_array($d) && isset($d['last']) && is_string($d['last'])) ? $d['last'] : '');
  if ($result === 'ok') $d[$how] = (int) (isset($d[$how]) ? $d[$how] : 0) + 1; else $d['failed'] = (int) (isset($d['failed']) ? $d['failed'] : 0) + 1;
  if ($how === 'postmark') $d['last'] = $result;
  @file_put_contents($file, json_encode($d), LOCK_EX);
}
function pas_mail_state() {
  $d = json_decode((string) @file_get_contents(dirname((string) $_SERVER['DOCUMENT_ROOT']) . '/phillyafterschool-mail.json'), true);
  return array('via' => pas_mail_via(), 'last' => (is_array($d) && isset($d['last']) && is_string($d['last'])) ? $d['last'] : '');
}
// Gives 1: sent. 0: the service won't send to this address (it bounced before, or the person marked our mail as spam),
// so don't try another way. -1: not sent here, use the host's mail.
function pas_postmark($fromName, $from, $to, $subject, $text, $html = '', $replyTo = '') {
  $key = pas_mail_key();
  if ($key === '' || !function_exists('curl_init')) return -1;
  $base = 'https://api.postmarkapp.com/email';
  if (PHP_SAPI === 'cli-server' && getenv('PAS_TEST_POSTMARK')) $base = (string) getenv('PAS_TEST_POSTMARK');   // the local test server only
  $msg = array(
    'From' => trim(preg_replace('/[<>",;\r\n]+/', '', (string) $fromName)) . ' <' . $from . '>', 'To' => (string) $to, 'Subject' => (string) $subject, 'TextBody' => (string) $text,
    'MessageStream' => 'outbound', 'TrackOpens' => false, 'TrackLinks' => 'None',   // we don't watch who opens or clicks
    'Headers' => array(array('Name' => 'Auto-Submitted', 'Value' => 'auto-generated'), array('Name' => 'X-Auto-Response-Suppress', 'Value' => 'All')),
  );
  if ((string) $html !== '') $msg['HtmlBody'] = (string) $html;
  if ((string) $replyTo !== '' && filter_var($replyTo, FILTER_VALIDATE_EMAIL) && !preg_match('/[\r\n]/', (string) $replyTo)) $msg['ReplyTo'] = (string) $replyTo;
  $json = json_encode($msg, JSON_UNESCAPED_UNICODE | JSON_INVALID_UTF8_SUBSTITUTE);
  if (!is_string($json)) return -1;
  $ch = curl_init($base);
  curl_setopt_array($ch, array(CURLOPT_POST => true, CURLOPT_RETURNTRANSFER => true, CURLOPT_CONNECTTIMEOUT => 4, CURLOPT_TIMEOUT => 8,
    CURLOPT_HTTPHEADER => array('Accept: application/json', 'Content-Type: application/json', 'X-Postmark-Server-Token: ' . $key), CURLOPT_POSTFIELDS => $json));
  $raw = curl_exec($ch);
  $code = (int) curl_getinfo($ch, CURLINFO_HTTP_CODE);
  curl_close($ch);
  $r = is_string($raw) ? json_decode($raw, true) : null;
  $err = (is_array($r) && isset($r['ErrorCode'])) ? (int) $r['ErrorCode'] : -1;
  if ($code === 200 && $err === 0) { pas_mail_note('postmark', 'ok'); return 1; }
  pas_mail_note('postmark', $err > 0 ? 'e' . $err : 'http' . $code);
  return $err === 406 ? 0 : -1;
}

$TO = "contact@phillyafterschool.org";
$SITE = "Philly After School";
$PROGRAMS = array("imagine-that-philly", "nebinger-clubs", "girls-on-the-run", "nebinger-arts-partners", "meredith-clubs", "coppin-clubs", "zhang-sah", "shot-tower-rec", "philly-inmovement", "settlement-kaleidoscope-plus", "philly-art-center-qv", "old-pine", "butchers-sew-shop", "mister-johns-music", "music-theatre-philly", "arden-drama-school", "walnut-street-theatre-school", "coco-academy", "queen-and-rook", "beehive-at-bok", "dandelion-after-school", "movemakers", "kids-on-12th", "columbus-square-rec", "hawthorne-cultural-center", "starr-garden-rec", "palumbo-rec", "mighty-writers-el-futuro", "free-library-leap", "fleisher-art-memorial", "makom-community", "vare-washington-edey", "vare-washington-clubs", "sunrise-mccall", "mccall-clubs", "sawubona-creativity-project", "playarts-day-camps", "philly-rock-gym-day-camps", "skate-the-foundry", "pafa-saturday-art", "moore-young-artists-workshop", "philadelphia-museum-of-art-kids", "made-institute-sunday-sewing", "rock-school-for-dance", "koresh-school-of-dance", "school-of-philadelphia-ballet", "zazz-dance", "temple-music-prep-cmsp", "wissahickon-skating-club", "penn-ice-rink", "starfinder-saturday-soccer", "franklin-institute-pacts", "macguffin-theatre", "philadelphia-dance-academy", "sunrise-kirkbride", "kirkbride-clubs", "sunrise-southwark", "southwark-clubs", "east-passyunk-rec");
$SCHOOLS = array("nebinger", "meredith", "coppin", "vare-washington", "mccall", "kirkbride", "southwark", "columbus-charter");

function fail($msg, $code) {
  http_response_code($code);
  header('Content-Type: text/html; charset=utf-8');
  echo '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Not sent</title><link rel="stylesheet" href="../assets/site.css?v=73b54e4c"></head><body><main class="wrap"><h1>That did not send</h1><p>' . htmlspecialchars($msg, ENT_QUOTES, 'UTF-8') . '</p><p><a href="javascript:history.back()">Go back to the form</a></p></main></body></html>';
  exit;
}
function field($key, $max) {
  $v = (isset($_POST[$key]) && is_string($_POST[$key])) ? trim($_POST[$key]) : '';
  $v = str_replace(chr(0), '', $v);
  return function_exists('mb_substr') ? mb_substr($v, 0, $max, 'UTF-8') : substr($v, 0, $max);
}
function one_line($v) {
  return trim(preg_replace('/[\r\n\t]+/', ' ', $v));
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
  header('Location: ./', true, 303);
  exit;
}
// A hidden field people never see. If it is filled in, a bot did it: act as if it worked.
if (field('company', 200) !== '') {
  header('Location: thanks/', true, 303);
  exit;
}

$program = one_line(field('program', 80));
$school = one_line(field('school', 40));
$stars = (int) field('stars', 2);
$name = one_line(field('name', 40));
$email = one_line(field('email', 150));
$comment = field('comment', 1200);

if (!in_array($program, $PROGRAMS, true) || !in_array($school, $SCHOOLS, true)) {
  fail('Please choose the program and school from the lists.', 400);
}
if ($stars < 1 || $stars > 5) {
  fail('Please choose a rating from 1 to 5 stars.', 400);
}
if (strlen($comment) < 20) {
  fail('Please write a sentence or two so other families know what to expect.', 400);
}
if ($name === '') {
  fail('Please add your first name. It is shown with your review.', 400);
}
if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
  fail('Please add a working email address. It is never shown.', 400);
}
if (field('firsthand', 5) !== 'yes') {
  fail('Please confirm this is your own experience.', 400);
}
if (substr_count(strtolower($comment), 'http') > 1) {
  fail('Reviews cannot include links. Please remove them and try again.', 400);
}

$entry = json_encode(array(
  'programId' => $program,
  'school' => $school,
  'name' => $name,
  'stars' => $stars,
  'comment' => trim(preg_replace('/\s+/', ' ', $comment)),
  'date' => date('Y-m-d'),
), JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);

$body = "New review, waiting for your approval.\n\n"
  . "Program: $program\n"
  . "School: $school\n"
  . "Stars: $stars\n"
  . "From: $name <$email>\n\n"
  . "$comment\n\n"
  . "To publish it, add this entry to data/reviews.json (inside the square brackets, with a comma between entries):\n\n"
  . "$entry\n";

$subject = one_line("[$SITE] Review: $program ($stars stars)");
$headers = array(
  'From: ' . $SITE . ' <' . $TO . '>',
  'Reply-To: ' . $email,
  'MIME-Version: 1.0',
  'Content-Type: text/plain; charset=UTF-8',
);

$sent = pas_postmark($SITE, $TO, $TO, $subject, $body, '', isset($email) ? (string) $email : '') === 1 || @mail($TO, '=?UTF-8?B?' . base64_encode($subject) . '?=', $body, implode("\r\n", $headers));
$log = dirname($_SERVER['DOCUMENT_ROOT']) . '/phillyafterschool-reviews.log';
$saved = @file_put_contents($log, date('c') . ($sent ? ' (emailed)' : ' (EMAIL FAILED)') . "\n" . $body . "----\n", FILE_APPEND | LOCK_EX);

if (!$sent && $saved === false) {
  fail('Something went wrong on our side. Please email ' . $TO . ' instead.', 500);
}
header('Location: thanks/', true, 303);
exit;
