<?php
// The edit page, behind a sign-in. Generated by build.mjs; edit it there.
$EDIT_USER = "Silverbauer";
$EDIT_HASH = '$2y$10$YM3U3P.TEB3.lr00uXCsbeNQW852A2Xdg/Rwbro4BIJULUT7bHiz2';
header('Cache-Control: no-store, private');
header('X-Robots-Tag: noindex');
function edit_key() {
  global $EDIT_HASH;
  static $k = null;
  if ($k !== null) return $k;
  $file = dirname($_SERVER['DOCUMENT_ROOT']) . '/phillyafterschool-edit.key';
  $raw = @file_get_contents($file);
  if ($raw === false || strlen(trim($raw)) !== 64) {
    $raw = bin2hex(random_bytes(32));
    if (@file_put_contents($file, $raw, LOCK_EX) === false) { http_response_code(503); exit('Signing in is not available right now.'); }
    @chmod($file, 0600);
    $raw = (string) @file_get_contents($file);   // if two requests raced, both read back the same key
  }
  $k = hash_hmac('sha256', $EDIT_HASH . '|edit-sign-in', trim($raw));
  return $k;
}
function edit_token($exp) {
  return $exp . '.' . hash_hmac('sha256', (string) $exp, edit_key());
}
function edit_signed_in() {
  if (!isset($_COOKIE['pas_edit']) || !is_string($_COOKIE['pas_edit'])) return false;
  $parts = explode('.', $_COOKIE['pas_edit'], 2);
  if (count($parts) !== 2 || !ctype_digit($parts[0]) || (int) $parts[0] < time()) return false;
  return hash_equals(edit_token($parts[0]), $_COOKIE['pas_edit']);
}

$https = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https');
function edit_cookie($value, $exp) {
  global $https;
  setcookie('pas_edit', $value, array('expires' => $exp, 'path' => '/edit/', 'secure' => $https, 'httponly' => true, 'samesite' => 'Lax'));
}
$error = '';
if (isset($_GET['out'])) {
  edit_cookie('', time() - 3600);
  header('Location: ./', true, 303);
  exit;
}
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  // Slow down guessing: at most 8 wrong tries from one address in 15 minutes.
  $file = dirname($_SERVER['DOCUMENT_ROOT']) . '/phillyafterschool-edit-signins.json';
  $who = substr(hash('sha256', isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : ''), 0, 16);
  $tries = @json_decode((string) @file_get_contents($file), true);
  if (!is_array($tries)) $tries = array();
  $recent = array();
  foreach ($tries as $k => $times) {
    if (!is_array($times)) continue;
    $keep = array();
    foreach ($times as $t) { if (is_int($t) && $t > time() - 900) $keep[] = $t; }
    if ($keep) $recent[$k] = $keep;
  }
  $user = (isset($_POST['user']) && is_string($_POST['user'])) ? trim($_POST['user']) : '';
  $pass = (isset($_POST['pass']) && is_string($_POST['pass'])) ? $_POST['pass'] : '';
  if (isset($recent[$who]) && count($recent[$who]) >= 8) {
    $error = 'Too many tries. Wait 15 minutes and try again.';
  } elseif (strcasecmp($user, $EDIT_USER) === 0 && password_verify($pass, $EDIT_HASH)) {
    $exp = time() + 30 * 86400;
    edit_cookie(edit_token($exp), $exp);
    header('Location: ./', true, 303);
    exit;
  } else {
    sleep(1);
    $recent[$who][] = time();
    @file_put_contents($file, json_encode($recent), LOCK_EX);
    $error = 'That username or password isn’t right.';
  }
}
if (!edit_signed_in()) {
  if ($error !== '') http_response_code(401);
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-MKNWQ3BC');</script>
<title>Sign in | Philly After School</title>
<meta name="description" content="Sign in to edit the words on this site.">
<link rel="canonical" href="https://phillyafterschool.org/edit/">
<meta name="robots" content="noindex">
<meta property="og:title" content="Sign in | Philly After School">
<meta property="og:description" content="Sign in to edit the words on this site.">
<meta property="og:type" content="website">
<meta property="og:url" content="https://phillyafterschool.org/edit/">
<meta property="og:site_name" content="Philly After School">
<meta property="og:image" content="https://phillyafterschool.org/share.png?v=5849280e">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="Philly After School: a row of Philadelphia rowhouses, a school and a yellow school bus">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="../favicon.svg" type="image/svg+xml">
<link rel="icon" href="../favicon.png" type="image/png" sizes="48x48">
<link rel="apple-touch-icon" href="../apple-touch-icon.png">
<meta name="theme-color" content="#96C9FF">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Archivo:wdth,wght@62..125,400..900&family=Atkinson+Hyperlegible:wght@400;700&display=swap">
<link rel="stylesheet" href="../assets/site.css?v=c406edff">
</head>
<body>
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MKNWQ3BC" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript><script>document.documentElement.className+=' js';try{if(localStorage.getItem('pas-in')==='1')document.documentElement.className+=' signed'}catch(e){}</script>
<div class="band topstrip when-out"><div class="topbar"><div class="in">
    <span>Already have an account?</span><a href="../account/">Log in</a>
  </div></div></div>
<header class="band sitebar">
  <div class="in bar">
    <a class="brand" href="../"><span class="bus-mark"></span>Philly After School</a>
    <button type="button" class="menu-btn" aria-expanded="false" aria-controls="site-nav"><span class="menu-bars" aria-hidden="true"></span>Menu</button>
    <nav class="nav" id="site-nav" aria-label="Site"><details class="menu"><summary>Programs</summary><ul><li><a href="../programs/">After-school programs</a></li><li><a href="../weekends/">Weekend classes</a></li><li><a href="../days-off/">Day-camp programs</a></li><li><a href="../summer-camps/">Summer camps</a></li></ul></details><details class="menu"><summary>Search by</summary><ul><li><a href="../schools/">School</a></li><li><a href="../neighborhoods/">Neighborhood</a></li><li><a href="../types/">Program type</a></li><li><a href="../programs/#by-day">Day of week</a></li></ul></details><details class="menu"><summary>Build a schedule<span class="count" data-board-count hidden></span></summary><ul><li><a href="../board/">After-school schedule</a></li><li><a href="../days-off/#plan">Day-camp schedule</a></li><li><a href="../summer-schedule/">Summer schedule</a></li><li><a href="../calendar/">My kids’ calendar</a></li></ul></details><details class="menu"><summary>Suggest</summary><ul><li><a href="../suggest/">A program</a></li><li><a href="../suggest/?kind=camp">A camp</a></li><li><a href="../suggest/?kind=correction">An update to a listing</a></li><li><a href="../ideas/">A feature</a></li><li><a href="../schools/request/">A school</a></li></ul></details><a href="../about/">About</a><a class="nav-cta when-out" href="../register/">Create a free account</a><a class="nav-cta when-in" href="../account/">Your account</a></nav>
  </div>
</header>
<div class="band pagehead">
  <div class="in hero">
    <h1>Sign in to edit</h1>
    <p class="lede">This page is for the people who look after the site’s wording.</p>
  </div>
  
</div>
<main class="wrap">
<div class="signin">
  <form class="form panel" method="post" action="./" data-edit-allow>
    <?php if ($error !== '') { ?><p class="flag" role="alert"><?php echo htmlspecialchars($error, ENT_QUOTES, 'UTF-8'); ?></p><?php } ?>
    <div class="field">
      <label for="e-user">Username</label>
      <input id="e-user" name="user" type="text" maxlength="60" autocomplete="username" autocapitalize="none" spellcheck="false" required>
    </div>
    <div class="field">
      <label for="e-pass">Password</label>
      <input id="e-pass" name="pass" type="password" maxlength="200" autocomplete="current-password" required>
    </div>
    <div><button class="btn primary big" type="submit">Sign in</button></div>
  </form>
</div>
</main>
<footer class="foot"><div class="in">
  <nav class="foot-cols" aria-label="Footer">
    <div class="foot-brand">
      <a class="brand" href="../"><span class="bus-mark"></span>Philly After School</a>
      <p><span data-copy="2ded0fc514">After-school programs in Philadelphia, sorted by the school your child goes to.</span></p>
      <p class="foot-support"><span><span data-copy="e877ba88ef">Free, and run by one parent.</span></span> <a class="btn foot-cta" href="../support/">Help the site keep going</a></p>
    </div>
    <div>
      <h2><a href="../schools/"><span data-copy="06c76a46e4">Schools</span></a></h2>
      <ul>
        <li><a href="../schools/"><span data-copy="0898b0b426">All schools</span></a></li>
        <li><a href="../neighborhoods/"><span data-copy="8ed176874c">By neighborhood</span></a></li>
        <li><a href="../schools/request/"><span data-copy="6c51011791">Ask for your school</span></a></li>
      </ul>
    </div>
    <div>
      <h2><a href="../programs/"><span data-copy="ab14d0a7db">Programs</span></a></h2>
      <ul>
        <li><a href="../programs/"><span data-copy="b8741ed7c0">All programs, A to Z</span></a></li>
        <li><a href="../types/"><span data-copy="3e6c889cad">Programs by type</span></a></li>
        <li><a href="../neighborhoods/"><span data-copy="3a356e1883">Programs by neighborhood</span></a></li>
        <li><a href="../weekends/"><span data-copy="65a1412e26">Weekend classes</span></a></li>
        <li><a href="../days-off/"><span data-copy="fb556467b7">Day-camp programs</span></a></li>
        <li><a href="../summer-camps/"><span data-copy="4f19f8d878">Summer camps</span></a></li>
        <li><a href="../suggest/"><span data-copy="0d1fc1aeaa">Suggest a program</span></a></li>
        <li><a href="../review/"><span data-copy="d2684e6248">Write a review</span></a></li>
      </ul>
    </div>
    <div>
      <h2><a href="../board/"><span data-copy="928655b7f0">Your family</span></a></h2>
      <ul>
        <li><a href="../board/"><span data-copy="55cf06857b">After-school schedule</span></a></li>
        <li><a href="../days-off/#plan"><span data-copy="ef8a7dc9b4">Day-camp schedule</span></a></li>
        <li><a href="../alerts/"><span data-copy="d4819c397f">Dates by email</span></a></li>
        <li><a href="../account/"><span data-copy="4ab2910209">Your account</span></a></li>
      </ul>
    </div>
    <div>
      <h2><a href="../about/"><span data-copy="6b21fb791a">About</span></a></h2>
      <ul>
        <li><a href="../about/"><span data-copy="5e461a2404">About this site</span></a></li>
        <li><a href="../about/#how"><span data-copy="5b2fc57ac3">How listings are checked</span></a></li>
        <li><a href="../about/#corrections"><span data-copy="1862eb688d">Send a correction</span></a></li>
        <li><a href="../contact/"><span data-copy="4832e45812">Contact us</span></a></li>
        <li><a href="../managers/"><span data-copy="c192560a97">For program managers</span></a></li>
        <li><a href="../ideas/"><span data-copy="29c269f6e8">Request a feature</span></a></li>
        <li><a href="../privacy/"><span data-copy="cf01481f62">Privacy</span></a></li>
        <li><a href="../terms/"><span data-copy="8a069ed1c6">Terms of use</span></a></li>
        <li><a href="../support/"><span data-copy="fd1482eac6">Buy me a coffee</span></a></li>
      </ul>
    </div>
  </nav>
  <div class="foot-fine">
    <p><span data-copy="b7e5078568">Listings come from each provider’s public pages and are not endorsements. Prices, hours and pickup routes change, so confirm with the provider before you enroll.</span></p>
    <p><span data-copy="ab9dba162b" data-tpl="{site} is an independent community project. It is not affiliated with the School District of Philadelphia or any provider listed." data-vars="{&quot;site&quot;:&quot;Philly After School&quot;}">Philly After School is an independent community project. It is not affiliated with the School District of Philadelphia or any provider listed.</span></p>
    <p><span data-copy="1ec7041a18">Questions?</span> <a href="mailto:contact@phillyafterschool.org">contact@phillyafterschool.org</a> <span data-copy="1758356db2">or</span> <a href="../contact/"><span data-copy="fa1e614bfa">send a message</span></a>.</p>
    <p>Built by <a href="https://joshsilverbauer.com" target="_blank" rel="noopener">Josh Silverbauer</a>.</p>
  </div>
</div></footer>
<script src="../assets/site.js?v=56c7c129" data-edit="{&quot;js&quot;:&quot;../assets/edit.js?v=29a85f54&quot;,&quot;send&quot;:&quot;../edit/send.php&quot;,&quot;home&quot;:&quot;../edit/&quot;,&quot;contact&quot;:&quot;contact@phillyafterschool.org&quot;}" data-api="../groups/api.php"></script>

</body>
</html>
<?php
  exit;
}
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-MKNWQ3BC');</script>
<title>Edit the copy | Philly After School</title>
<meta name="description" content="Edit the words on this site.">
<link rel="canonical" href="https://phillyafterschool.org/edit/">
<meta name="robots" content="noindex">
<meta property="og:title" content="Edit the copy | Philly After School">
<meta property="og:description" content="Edit the words on this site.">
<meta property="og:type" content="website">
<meta property="og:url" content="https://phillyafterschool.org/edit/">
<meta property="og:site_name" content="Philly After School">
<meta property="og:image" content="https://phillyafterschool.org/share.png?v=5849280e">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="Philly After School: a row of Philadelphia rowhouses, a school and a yellow school bus">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="../favicon.svg" type="image/svg+xml">
<link rel="icon" href="../favicon.png" type="image/png" sizes="48x48">
<link rel="apple-touch-icon" href="../apple-touch-icon.png">
<meta name="theme-color" content="#96C9FF">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Archivo:wdth,wght@62..125,400..900&family=Atkinson+Hyperlegible:wght@400;700&display=swap">
<link rel="stylesheet" href="../assets/site.css?v=c406edff">
</head>
<body>
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MKNWQ3BC" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript><script>document.documentElement.className+=' js';try{if(localStorage.getItem('pas-in')==='1')document.documentElement.className+=' signed'}catch(e){}</script>
<div class="band topstrip when-out"><div class="topbar"><div class="in">
    <span>Already have an account?</span><a href="../account/">Log in</a>
  </div></div></div>
<header class="band sitebar">
  <div class="in bar">
    <a class="brand" href="../"><span class="bus-mark"></span>Philly After School</a>
    <button type="button" class="menu-btn" aria-expanded="false" aria-controls="site-nav"><span class="menu-bars" aria-hidden="true"></span>Menu</button>
    <nav class="nav" id="site-nav" aria-label="Site"><details class="menu"><summary>Programs</summary><ul><li><a href="../programs/">After-school programs</a></li><li><a href="../weekends/">Weekend classes</a></li><li><a href="../days-off/">Day-camp programs</a></li><li><a href="../summer-camps/">Summer camps</a></li></ul></details><details class="menu"><summary>Search by</summary><ul><li><a href="../schools/">School</a></li><li><a href="../neighborhoods/">Neighborhood</a></li><li><a href="../types/">Program type</a></li><li><a href="../programs/#by-day">Day of week</a></li></ul></details><details class="menu"><summary>Build a schedule<span class="count" data-board-count hidden></span></summary><ul><li><a href="../board/">After-school schedule</a></li><li><a href="../days-off/#plan">Day-camp schedule</a></li><li><a href="../summer-schedule/">Summer schedule</a></li><li><a href="../calendar/">My kids’ calendar</a></li></ul></details><details class="menu"><summary>Suggest</summary><ul><li><a href="../suggest/">A program</a></li><li><a href="../suggest/?kind=camp">A camp</a></li><li><a href="../suggest/?kind=correction">An update to a listing</a></li><li><a href="../ideas/">A feature</a></li><li><a href="../schools/request/">A school</a></li></ul></details><a href="../about/">About</a><a class="nav-cta when-out" href="../register/">Create a free account</a><a class="nav-cta when-in" href="../account/">Your account</a></nav>
  </div>
</header>
<div class="band pagehead">
  <div class="in hero">
    <h1>Edit the words on this site</h1>
    <p class="lede">Turn on editing, then click a sentence on any page and type. Nothing changes for visitors until your edits are sent and approved.</p>
  </div>
  
</div>
<main class="wrap">
<div class="prose" data-edit-page>
  <div class="panel">
    <h2 id="edit-state">Editing is off</h2>
    <p id="edit-state-text">Turn it on and a bar appears at the bottom of every page.</p>
    <div class="actions"><button type="button" class="btn primary big needs-js" id="edit-start">Start editing</button><button type="button" class="btn needs-js" id="edit-stop" hidden>Stop editing</button></div>
    <noscript><p>Editing needs JavaScript turned on.</p></noscript>
  </div>
  <p class="hint">You’re signed in on this device for 30 days. <a href="?out=1">Sign out</a></p>
  <p><a class="btn" href="stats/">Site numbers: accounts, shared weeks and groups</a> <a class="btn" href="claims/">Claims and proposed changes</a></p>
  <h2>How it works</h2>
  <ol>
    <li>Click any text with a dotted outline and type. Text you’ve changed turns yellow.</li>
    <li>Move between pages with the menu or the list below. Your edits are kept in this browser as you go, so stay on the same phone or computer until you’ve sent them.</li>
    <li>Choose “Review and send” in the bar at the bottom. You’ll see each change next to the original and can undo any of them.</li>
    <li>Sending emails the changes to be approved. They appear on the site once they’re published.</li>
  </ol>
  <h2>Pages</h2>
  <ul>
    <li><a href="../">Home</a></li>
    <li><a href="../schools/">Schools</a></li>
    <li><a href="../schools/request/">A school that isn’t covered yet</a></li>
    <li><a href="../nebinger/">Nebinger page</a></li>
    <li><a href="../meredith/">Meredith page</a></li>
    <li><a href="../coppin/">Coppin page</a></li>
    <li><a href="../vare-washington/">Vare-Washington page</a></li>
    <li><a href="../mccall/">McCall page</a></li>
    <li><a href="../types/">Program types</a></li>
    <li><a href="../types/aftercare/">A type page (Aftercare)</a></li>
    <li><a href="../programs/">All programs, A to Z</a></li>
    <li><a href="../neighborhoods/">Neighborhoods</a></li>
    <li><a href="../neighborhoods/queen-village/">A neighborhood page (Queen Village)</a></li>
    <li><a href="../programs/imagine-that-philly/">A program page (Imagine That Philly)</a></li>
    <li><a href="../board/">Build your week</a></li>
    <li><a href="../suggest/">Suggest a program</a></li>
    <li><a href="../suggest/thanks/">Thank-you page after a suggestion</a></li>
    <li><a href="../ideas/">Request a feature</a></li>
    <li><a href="../ideas/thanks/">Thank-you page after an idea</a></li>
    <li><a href="../review/">Write a review</a></li>
    <li><a href="../review/thanks/">Thank-you page after a review</a></li>
    <li><a href="../about/">About</a></li>
    <li><a href="../privacy/">Privacy</a></li>
    <li><a href="../support/">Buy me a coffee</a></li>
    <li><a href="../404.html">Page not found</a></li>
  </ul>
  <h2>What can’t be edited here</h2>
  <ul>
    <li>Program details: names, descriptions, hours and costs come from the listings data. Send fixes for those through <a href="../suggest/">the suggestion form</a>.</li>
    <li>Menu labels, text that changes as you click (filter counts, the roster), the grey example text inside boxes, and the choices inside drop-downs.</li>
    <li>Words in curly braces, like {school}, are filled in for each page. Leave them in the sentence.</li>
  </ul>
</div>
</main>
<footer class="foot"><div class="in">
  <nav class="foot-cols" aria-label="Footer">
    <div class="foot-brand">
      <a class="brand" href="../"><span class="bus-mark"></span>Philly After School</a>
      <p><span data-copy="2ded0fc514">After-school programs in Philadelphia, sorted by the school your child goes to.</span></p>
      <p class="foot-support"><span><span data-copy="e877ba88ef">Free, and run by one parent.</span></span> <a class="btn foot-cta" href="../support/">Help the site keep going</a></p>
    </div>
    <div>
      <h2><a href="../schools/"><span data-copy="06c76a46e4">Schools</span></a></h2>
      <ul>
        <li><a href="../schools/"><span data-copy="0898b0b426">All schools</span></a></li>
        <li><a href="../neighborhoods/"><span data-copy="8ed176874c">By neighborhood</span></a></li>
        <li><a href="../schools/request/"><span data-copy="6c51011791">Ask for your school</span></a></li>
      </ul>
    </div>
    <div>
      <h2><a href="../programs/"><span data-copy="ab14d0a7db">Programs</span></a></h2>
      <ul>
        <li><a href="../programs/"><span data-copy="b8741ed7c0">All programs, A to Z</span></a></li>
        <li><a href="../types/"><span data-copy="3e6c889cad">Programs by type</span></a></li>
        <li><a href="../neighborhoods/"><span data-copy="3a356e1883">Programs by neighborhood</span></a></li>
        <li><a href="../weekends/"><span data-copy="65a1412e26">Weekend classes</span></a></li>
        <li><a href="../days-off/"><span data-copy="fb556467b7">Day-camp programs</span></a></li>
        <li><a href="../summer-camps/"><span data-copy="4f19f8d878">Summer camps</span></a></li>
        <li><a href="../suggest/"><span data-copy="0d1fc1aeaa">Suggest a program</span></a></li>
        <li><a href="../review/"><span data-copy="d2684e6248">Write a review</span></a></li>
      </ul>
    </div>
    <div>
      <h2><a href="../board/"><span data-copy="928655b7f0">Your family</span></a></h2>
      <ul>
        <li><a href="../board/"><span data-copy="55cf06857b">After-school schedule</span></a></li>
        <li><a href="../days-off/#plan"><span data-copy="ef8a7dc9b4">Day-camp schedule</span></a></li>
        <li><a href="../alerts/"><span data-copy="d4819c397f">Dates by email</span></a></li>
        <li><a href="../account/"><span data-copy="4ab2910209">Your account</span></a></li>
      </ul>
    </div>
    <div>
      <h2><a href="../about/"><span data-copy="6b21fb791a">About</span></a></h2>
      <ul>
        <li><a href="../about/"><span data-copy="5e461a2404">About this site</span></a></li>
        <li><a href="../about/#how"><span data-copy="5b2fc57ac3">How listings are checked</span></a></li>
        <li><a href="../about/#corrections"><span data-copy="1862eb688d">Send a correction</span></a></li>
        <li><a href="../contact/"><span data-copy="4832e45812">Contact us</span></a></li>
        <li><a href="../managers/"><span data-copy="c192560a97">For program managers</span></a></li>
        <li><a href="../ideas/"><span data-copy="29c269f6e8">Request a feature</span></a></li>
        <li><a href="../privacy/"><span data-copy="cf01481f62">Privacy</span></a></li>
        <li><a href="../terms/"><span data-copy="8a069ed1c6">Terms of use</span></a></li>
        <li><a href="../support/"><span data-copy="fd1482eac6">Buy me a coffee</span></a></li>
      </ul>
    </div>
  </nav>
  <div class="foot-fine">
    <p><span data-copy="b7e5078568">Listings come from each provider’s public pages and are not endorsements. Prices, hours and pickup routes change, so confirm with the provider before you enroll.</span></p>
    <p><span data-copy="ab9dba162b" data-tpl="{site} is an independent community project. It is not affiliated with the School District of Philadelphia or any provider listed." data-vars="{&quot;site&quot;:&quot;Philly After School&quot;}">Philly After School is an independent community project. It is not affiliated with the School District of Philadelphia or any provider listed.</span></p>
    <p><span data-copy="1ec7041a18">Questions?</span> <a href="mailto:contact@phillyafterschool.org">contact@phillyafterschool.org</a> <span data-copy="1758356db2">or</span> <a href="../contact/"><span data-copy="fa1e614bfa">send a message</span></a>.</p>
    <p>Built by <a href="https://joshsilverbauer.com" target="_blank" rel="noopener">Josh Silverbauer</a>.</p>
  </div>
</div></footer>
<script src="../assets/site.js?v=56c7c129" data-edit="{&quot;js&quot;:&quot;../assets/edit.js?v=29a85f54&quot;,&quot;send&quot;:&quot;../edit/send.php&quot;,&quot;home&quot;:&quot;../edit/&quot;,&quot;contact&quot;:&quot;contact@phillyafterschool.org&quot;}" data-api="../groups/api.php"></script>

</body>
</html>
